account/urls.py
from django.urls import path
import account.views as views 

app_name = 'account'

urlpatterns = [
    path('login', views.login_user, name='login'),
    path('register', views.register_user, name='register'),
    path('register_ajax', views.register_ajax, name='register_ajax'),
    path('logout', views.logout_user, name='logout'),
    path('show_user', views.show_user, name='show_user'),
    path('view_profile/<int:id>', views.view_profile, name='view_profile'),
    path('edit_profile/<int:id>', views.edit_profile, name='edit_profile'),
    path('change_password/<int:id>', views.change_password, name='change_password'),
    path('delete_profile/<int:id>', views.delete_profile, name='delete_profile'),
    path('admin', views.account_admin_dashboard, name='account_admin_dashboard'),
    path('admin/edit_profile/<int:id>', views.admin_edit_profile, name='admin_edit_profile'),
    # flutter:
    path('api/login/', views.login_flutter, name='login_flutter'),
    path('api/register/', views.register_flutter, name='register_flutter'),
    path('api/logout/', views.logout_flutter, name='logout_flutter'),
    path('api/current_user_id/', views.current_user_id, name='current_user_id'),
    path('api/view_profile/<int:id>/', views.view_profile_flutter, name='view_profile_flutter'),
    path('api/edit_profile/<int:id>/', views.edit_profile_flutter, name='edit_profile_flutter'),
    path('api/change_password/<int:id>/', views.change_password_flutter, name='change_profile_flutter'),
    path('api/delete_profile/<int:id>/', views.delete_profile_flutter, name='delete_profile_flutter'),
    path('api/admin/', views.account_admin_flutter, name='account_admin_flutter'),
    path('api/admin/edit_profile/<int:id>/', views.admin_edit_profile_flutter, name='admin_edit_profil_flutter'),
]

homepage/urls.py
from django.urls import path
from homepage.views import show_homepage, create_spot,show_spot, proxy_image, json_spots
from homepage.views import delete_spot, edit_spot, get_user_nobar_spots, create_spot_flutter
from homepage.views import delete_spot_flutter, edit_spot_flutter, json_my_spot
app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
    path('create-spot/',create_spot, name='create_spot'),
    path('spot/<str:id>/',show_spot,name='show_spot'),
    path('spot/<uuid:id>/delete', delete_spot,name='delete_spot'),
    path('json/', json_spots, name='json_spots'),
    path('json-mine/', json_my_spot, name='json_mine'),
    path('spot/<uuid:id>/edit', edit_spot, name='edit_spot'),
    path('user-spots-json/', get_user_nobar_spots, name='get_user_nobar_spots'),
    path('proxy-image/', proxy_image, name='proxy_image'),
    path('create-spot-flutter/',create_spot_flutter,name='create-spot-flutter'),
    path('delete-spot-flutter/<uuid:id>/',delete_spot_flutter,name='delete-spot-flutter'),
    path('edit-spot-flutter/<uuid:id>/', edit_spot_flutter, name='edit-spot-flutter'),
]

join/urls.py
from django.urls import path
from join.views import show_join, post_join, get_join, update_join, delete_join, create_join_flutter, update_join_flutter, delete_join_flutter

app_name = 'join'

urlpatterns = [
    path('', show_join, name='show_join'),
    path('post/<uuid:nobar_place_id>/', post_join, name='post_join'),
    path('get/', get_join, name='get_join'),
    path('update/<uuid:id>/', update_join, name='update_join'),
    path('delete/<uuid:id>/', delete_join, name='delete_join'),
    path('create-flutter/', create_join_flutter, name='create_join_flutter'),
    path('update-flutter/<uuid:id>/', update_join_flutter, name='update_join_flutter'),
    path('delete-flutter/<uuid:id>/', delete_join_flutter, name='delete_join_flutter'),
]

nobarpedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('join/', include('join.urls')),
    path('review/', include('review.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('match/', include('match.urls')),
    path('', include('homepage.urls')),
]

# Untuk serve profile picture
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Proxy model buat data diri user
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=100)
    bio = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(upload_to='account/profile_pics', blank=True, null=True)
    
    def __str__(self):
        return self.user.username
    

account/views.py
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from account.forms import AdminUserEditForm, CustomUserCreationForm, CustomUserEditForm

from account.models import Profile
from django.contrib.auth.models import User

from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
import json

'''
Note: 
admin punya 3 permission: 
auth.view_user
auth.delete_user 
auth.change_user
'''

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            # cek apakah user adalah admin menggunakan permission
            if not user.has_perm('auth.view_user'):                
                response = HttpResponseRedirect(reverse("homepage:show_homepage"))
            else:
                response = HttpResponseRedirect(reverse("account:account_admin_dashboard"))
            # response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def register_user(request):
    form = CustomUserCreationForm()
    # if request.method == "POST":
    #     form = CustomUserCreationForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         user = form.save()
    #         user.save()
    #         messages.success(request, 'Your account has been successfully created!')
    #         return redirect('account:login')
    
    context = {'form': form}
    return render(request, 'register.html', context)
  
def register_ajax(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return JsonResponse({"success": True, "message": "Account created successfully!"})
        else:
            # Return form errors in JSON
            return JsonResponse({"success": False, "errors": form.errors})
    return JsonResponse({"success": False, "message": "Invalid request method."}, status=400)
  
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('account:login'))
    # response.delete_cookie('last_login')
    return response

def view_profile(request, id):
    show_update_button = False
    if (request.user.id == id):
        show_update_button = True
        
    user = get_object_or_404(User, pk=id)
    context = {"user" : user, "show_update_button": show_update_button}
    return render(request, "view_profile.html", context)

@login_required(login_url='/account/login')
def edit_profile(request, id):
    if request.user.id != id:
        # print('ga boleh edit punya orang  lain bro', request.user.id, " ", id)
        return HttpResponseRedirect(reverse('homepage:show_homepage'))
    user = get_object_or_404(User, pk=id)
    if request.method == 'POST':
        form = CustomUserEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'User profile updated successfully!')
            return redirect('account:view_profile', id=id)
    else:
        form = CustomUserEditForm(instance=user)
    context = {'form': form }
    return render(request, "edit_profile.html", context)
  
@login_required(login_url='/account/login')
# @csrf_exempt
def delete_profile(request, id):
    # Hanya dirinya sendiri atau ADMIN yg boleh delete
    if not request.user.has_perm('auth.delete_user') and request.user.id != id:
        return HttpResponseRedirect(reverse('homepage:show_homepage'))

    user_to_delete = get_object_or_404(User, pk=id)
    is_admin = request.user.has_perm('auth.delete_user')

    user_to_delete.delete()

    if is_admin:
        # Kalo admin yang delete, balik ke dashboard admin
        return HttpResponseRedirect(reverse('account:account_admin_dashboard'))
    else:
        # Kalo dirinya sendiri yg delete, arahkan ke login
        return HttpResponseRedirect(reverse('account:login'))

# @login_required(login_url='/account/login')
# def delete_profile_from_admin(request, id):
#   if not request.user.is_staff:
#     return HttpResponseRedirect(reverse('account:admin'))
#   user = get_object_or_404(User, pk=id)
#   user.delete()
#   return HttpResponseRedirect(reverse('account:admin'))
  
@login_required(login_url='/account/login')
def change_password(request, id):
    if request.user.id != id:
        print('ga boleh edit punya orang  lain bro', request.user.id, " ", id)
        return HttpResponseRedirect(reverse('homepage:show_homepage'))
    
    user = get_object_or_404(User, pk=id)
    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user) # agar user ga ke logout otomatis, langsung update session dengan password yg baru
            #messages.success(request, 'Your password was successfully updated!')
            return redirect('account:edit_profile', id=id)
        #else:
            #messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(user)

    return render(request, 'change_password.html', {'form': form})

@login_required(login_url='/account/login')
def show_user(request):
    return JsonResponse(data=[{'msg':'this is user page'}], safe=False)

@login_required(login_url='/account/login')
def account_admin_dashboard(request):
    if not request.user.has_perm('auth.view_user'):
        return HttpResponseRedirect(reverse('homepage:show_homepage'))
        
    users = User.objects.all()
    context = {'users': users}
    return render(request, "account_admin_dashboard.html", context)

@login_required(login_url='/account/login')
def admin_edit_profile(request, id):
    if not request.user.has_perm('auth.change_user'):
        return HttpResponseRedirect(reverse('homepage:show_homepage'))

    user_to_edit = get_object_or_404(User, pk=id)
    
    if request.method == 'POST':
        form = AdminUserEditForm(request.POST, request.FILES, instance=user_to_edit)
        if form.is_valid():
            form.save()
            messages.success(request, 'User profile updated successfully!')
            return redirect('account:account_admin_dashboard')
    else:
        form = AdminUserEditForm(instance=user_to_edit)

    context = {'form': form, 'user_to_edit': user_to_edit}
    return render(request, "admin_edit_profile.html", context)


# API for FLUTTER APP
@csrf_exempt
def login_flutter(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # Login status successful.
            
            is_admin = request.user.has_perm('auth.delete_user')  
            
            return JsonResponse({
                "username": user.username,
                "status": True,
                "is_admin": is_admin,
                "message": "Login successful!"
                # Add other data if you want to send data to Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login failed, account is disabled."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login failed, please check your username or password."
        }, status=401)


@csrf_exempt
def register_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data['username']
        password1 = data['password1']
        password2 = data['password2']

        # Check if the passwords match
        if password1 != password2:
            return JsonResponse({
                "status": False,
                "message": "Passwords do not match."
            }, status=400)
        
        # Check if the username is already taken
        if User.objects.filter(username=username).exists():
            return JsonResponse({
                "status": False,
                "message": "Username already exists."
            }, status=400)
        
        # Create the new user
        user = User.objects.create_user(username=username, password=password1)
        user.save()
        
        return JsonResponse({
            "username": user.username,
            "status": 'success',
            "message": "User created successfully!"
        }, status=200)
    
    else:
        return JsonResponse({
            "status": False,
            "message": "Invalid request method."
        }, status=400)
    

@csrf_exempt
def logout_flutter(request):
    username = request.user.username
    try:
        logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logged out successfully!"
        }, status=200)
    except:
        return JsonResponse({
            "status": False,
            "message": "Logout failed."
        }, status=401)

@login_required
def current_user_id(request):
    is_admin = request.user.has_perm('auth.delete_user')  
    return JsonResponse({
        "id": request.user.id,
        "username": request.user.username,
        "is_admin": is_admin,
    })
        
def view_profile_flutter(request, id):
    user = get_object_or_404(User, pk=id)

account/templates/account_admin_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Admin Dashboard - Account</title>
{% endblock meta %}

{% block content %}
{% include 'navbar-admin.html' %} 
<div class="hidden">{% csrf_token %}</div>
{% include 'delete_modal.html' %}

<style>
.user-element {
    background: #333;
    color: white;
    padding: 1rem 1.5rem;
    border-radius: 8px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 0.75rem;
}
.user-element:hover {
    background: #444;
}
.btn-edit, .btn-delete {
  transition: transform 0.25s ease, box-shadow 0.25s ease;
}
.btn-edit:hover, .btn-delete:hover {
  transform: scale(1.30);
}
</style>

<div class="min-h-screen bg-[#1E1E1E] pt-[100px] pb-10">
    <div class="w-full max-w-[800px] mx-auto px-4">
        
        <h1 class="text-3xl font-bold text-white mb-6">User Management</h1>
        
        {% if messages %}
        <div id="message-container" class="mb-6 space-y-3">
          {% for message in messages %}
            {% if message.tags == 'success' %}
              <div class="px-4 py-3 text-sm text-green-200">
                {{ message }}
              </div>
            {% elif message.tags == 'error' %}
              <div class="px-4 py-3 text-sm text-red-200">
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        </div>
        {% endif %}
      
        <div class="flex flex-col">
            {% for user in users %}
            <div class="user-element" id="user-row-{{ user.id }}">
                <div class="flex gap-4 items-center">
                    {% if user.profile.profile_picture %}
                        <img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture"
                            class="w-[50px] h-[50px] rounded-full border-2 border-green-600 object-cover">
                    {% else %}
                        <img src="{% static 'image/no-profile-picture.svg' %}" alt="No Profile Picture"
                            class="w-[50px] h-[50px] rounded-full border-2 border-green-600 object-cover">
                    {% endif %}
                    <span class="font-medium text-lg">{{ user.username }} {% if perms.auth.view_user %}(Admin){% endif %}</span>
                </div>
                <div class="flex items-center gap-4">
                    <a href="{% url 'account:admin_edit_profile' user.id %}" class="btn-edit">
                        <img src="{% static 'image/edit-outline.svg' %}"> </img>
                    </a>
                    
                    <button type="button" 
                            onclick="showDeleteModal({user_id: {{ user.id }} })" 
                            class="btn-delete">
                        <img src="{% static 'image/delete-outline.svg' %}"> </img>
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<script>
setTimeout(() => {
    document.getElementById('message-container').classList.add('hidden');
}, 4000)

</script>


{% endblock %}

account/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Edit Profile</title>
{% endblock meta %}

{% block content %}

{% include 'delete_modal.html' %}

{% if not perms.auth.view_user %}
{% include 'navbar.html' %}
{% else %}
{% include 'navbar-admin.html' %}
{% endif %}


<style>
.input-bar {
    border-radius: 8px;
    border: 1px solid var(--Neutral-700, #666);
    background: var(--Neutral-900, #333);
    color: white;
    padding: 10px 14px;
    width: 100%;
}
.input-bar:focus {
    outline: none;
    border-color: #2CAC5C;
}
.btn-save {
    border-radius: 8px;
    border: 1px solid #6ADE7F;
    background: #2CAC5C;
    color: white;
    padding: 10px 28px;
    transition: background 0.2s ease;
    font-weight: 500;
}
.btn-save:hover {
    background: #23994E;
}
.btn-cancel {
    border-radius: 8px;
    border: 1px solid #666;
    background: #333;
    color: #ccc;
    padding: 10px 28px;
    transition: background 0.2s ease;
    font-weight: 500;
}
.btn-cancel:hover {
    background: #444;
}

.btn-danger {
    border-radius: 8px;
    border: 1px solid #e53e3e;
    background: #333;
    color: #f56565;
    padding: 10px 28px;
    transition: all 0.2s ease;
    font-weight: 500;
    width: 100%;
}
.btn-danger:hover {
    background: #4a1d1d;
    color: #fc8181;
}
.btn-secondary {
    border-radius: 8px;
    border: 1px solid #d69e2e;
    background: #333;
    color: #f6e05e;
    padding: 10px 28px;
    transition: all 0.2s ease;
    font-weight: 500;
    width: 100%;
}
.btn-secondary:hover {
    background: #4a401d;
    color: #faf089;
}
</style>

<div class="min-h-screen bg-[#1E1E1E] flex flex-col items-center justify-center pt-[100px] pb-10">
  <div class="bg-[#333] w-full max-w-[600px] rounded-[12px] px-10 py-8 shadow-sm">
      
      <div class="mb-8">
        <h1 class="text-2xl font-bold text-white mb-2">Edit Profile</h1>
      </div>

      {% if form.instance.profile.profile_picture %}
        <img src="{{ form.instance.profile.profile_picture.url }}" alt="Profile Picture"
             class="w-32 h-32 mx-auto rounded-full border-4 border-green-600 object-cover mb-4">
      {% else %}
        <img src="{% static 'image/no-profile-picture.svg' %}" alt="No Profile Picture"
             class="w-32 h-32 mx-auto rounded-full border-4 border-green-600 object-cover mb-4">
      {% endif %}

      {% if form.non_field_errors %}
        <div class="mb-6 space-y-2">
          {% for error in form.non_field_errors %}
            <div class="text-sm text-red-300">
              {{ error }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

      {% if form.errors %}
        <div class="mb-6 space-y-2">
          {% for field, errors in form.errors.items %}
            {% if field != '__all__' %}
              {% for error in errors %}
                <div class="text-sm text-red-300">
                  <strong>{{ field|title }}:</strong> {{ error }}
                </div>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      
      <form method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
          
        <div>
          <label for="username" class="block body mb-2 text-white">Username</label>
          <input 
            id="username" 
            name="username"
            value="{{ form.username.value|default:'' }}"
            type="text" 
            required 
            class="w-full input-bar" 
            placeholder="Choose a username">
        </div>

        <div>
          <label for="email" class="block body mb-2 text-white">Email</label>
          <input 
            id="email" 
            name="email" 
            type="email"
            value="{{ form.email.value|default:'' }}"
            class="w-full input-bar" 
            placeholder="Enter your Email">
        </div>

        <div>
          <label for="fullname" class="block body mb-2 text-white">Full Name</label>
          <input 
              id="fullname" 
              name="fullname" 
              type="text" 
              value="{{ form.fullname.value|default:'' }}"
              maxlength="100" 
              class="w-full input-bar" 
              placeholder="Enter your full name">
        </div>

        <div>
          <label for="bio" class="block body mb-2 text-white">Bio</label>
          <textarea 
              id="bio" 
              name="bio" 
              rows="3"
              class="w-full input-bar resize-none" 
              placeholder="Tell something about yourself">{{ form.bio.value|default:'' }}</textarea>
        </div>

        <div>
          <label for="profile_picture" class="block body mb-2 text-white">Profile Picture</label>
          {% if form.profile_picture.value %}
            <p class="text-sm text-gray-400 mb-2">Current: <a href="{{ form.profile_picture.value.url }}" class="text-green-400" target="_blank">{{ form.profile_picture.value.name }}</a></p>
          {% endif %}
          <input 
              id="profile_picture" 
              name="profile_picture" 
              type="file" 
              accept="image/*" 
              class="w-full text-white file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-green-600 file:text-white hover:file:bg-green-700">
        </div>
        
        <div class="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-600">
          <a id="backButton" class="backButton order-2 sm:order-1 btn-cancel text-center">
            Cancel
          </a>
          <button type="submit" class="order-1 sm:order-2 flex-1 btn-save">
            Update Profile
          </button>
        </div>

        <div class="space-y-4 pt-6 border-t border-gray-600">
          <button type="button" id="changePasswordButton" class="btn-secondary">
            Change Password
          </button>
          <button type="button" id="deleteButton" class="btn-danger">
            Delete Account
          </button>
        </div>

      </form>
    </div>
</div>

<script>

const deleteButton = document.getElementById('deleteButton');
const changePasswordButton = document.getElementById('changePasswordButton');
const user_id = {{ form.instance.id }};

const backButtons = document.querySelectorAll('.backButton');
backButtons.forEach((el) => {
    setTimeout(() => {
        const back_url = "{% url 'account:view_profile' 0 %}".replace('0', user_id);
        el.href = back_url;
    }, 10);
});

deleteButton.addEventListener('click', (e) => {
  e.preventDefault(); 
  showDeleteModal({user_id: user_id });
});

changePasswordButton.addEventListener('click', (e) => {
  e.preventDefault(); 
  const url_address = "{% url 'account:change_password' 0 %}".replace('0', user_id);
  setTimeout(() => {
      window.location.href = url_address;
  }, 10);
});



</script>
{% endblock %}

account/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login - NobarPedia</title>
{% endblock meta %}

{% block content %}
<style>
.join-us {
    font-family: "Poppins", sans-serif;
    font-size: 40px;
    font-style: normal;
    font-weight: 600;
    line-height: normal;
}

.input-bar {
    border-radius: 8px;
    border: 1px solid var(--Neutral-700, #666);
    background: var(--Neutral-900, #333);
    color: white;
}

.btn-signin {
    border-radius: 8px;
    border: 1px solid #6ADE7F;
    background: #2CAC5C;
    color: white;
    padding: 8px 28px;
}
</style>

<div class="min-h-screen bg-[#1E1E1E] flex items-center justify-center p-8">
    <div class="flex flex-col md:flex-row w-full relative z-10">
        <!-- Section Kiri: Image -->
        <div class="hidden md:flex w-1/2 flex-col justify-between items-center">
            <!-- Blurry Rectangle -->
            <div class="absolute bottom-10 left-0 w-full h-[300px] bg-[#0a463241]/50 blur-3xl -z-10"></div>
            <!-- Image dan Headline -->
            <img src="{% static 'image/register-frame.png' %}" class="max-w-[749px] w-full h-auto object-contain z-10"></img>
            <h1 class="text-center text-[58px] z-10"> Login to Nobarpedia </h1>
            <h2 class="text-center headline z-10 pb-10"> Join a Nobar Spot by first logging in </h1>
        </div>
        <!-- Section Kanan: Form Register -->
        <div class="bg-[#333] w-full md:w-1/2 rounded-[12px] px-16 py-6 shadow-sm">
            <div class="text-center mb-8">
                <h4 class="join-us">Sign In</h4>
            </div>

      <!-- Form Errors Display -->
      {% if form.non_field_errors %}
        <div class="mb-6">
          {% for error in form.non_field_errors %}
            <div class="text-sm text-red-200">
              {{ error }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

      {% if form.errors %}
        <div class="mb-6">
          {% for field, errors in form.errors.items %}
            {% if field != '__all__' %}
              {% for error in errors %}
                <div class="text-sm red text-red-200">
                  <strong>{{ field|title }}:</strong> {{ error }}
                </div>
              {% endfor %}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}

      <form method="POST" action="" class="space-y-6">
        {% csrf_token %}
        
        <div>
            <label for="username" class="block body mb-4">Username</label>
            <input 
            id="username" 
            name="username" 
            type="text" 
            required 
            class="w-full px-4 py-3 input-bar focus:outline-none focus:border-green-500 transition duration-200" 
            placeholder="Enter your username">
        </div>

        <div>
            <label for="password1" class="block body mb-4">Password</label>
            <input 
            id="password" 
            name="password" 
            type="password" 
            required 
            class="w-full px-4 py-3 input-bar focus:outline-none focus:border-green-500 transition duration-200" 
            placeholder="Enter your password">
        </div>

        <button 
          type="submit" 
          class="w-full btn-signin headline font-medium rounded hover:bg-green-700 transition duration-200">
          Sign In
        </button>
      </form>

      <!-- Messages Display -->
      {% if messages %}
        <div class="mt-6">
          {% for message in messages %}
            <div 
              class="
                px-4 py-3  text-sm 
                {% if message.tags == 'success' %}
                  text-green-200
                {% elif message.tags == 'error' %}
                 text-red-200
                {% else %}
                  text-gray-200
                {% endif %}
              ">
              {{ message }}
            </div>
          {% endfor %}
        </div>
      {% endif %}

        <div class="mt-16 text-center flex flex-col gap-1">
            <p class="footnote">
                Don't have an account? <a href="{% url 'account:register' %}" class="text-green-600 hover:text-green-700">Register Now</a>
            </p>
            <p class="footnote">Or</p>
            <p class="footnote">
                Continue as <a href="{% url 'homepage:show_homepage' %}" class="text-green-600 hover:text-green-700">Guest</a>
            </p> 
        </div>
    </div>
  </div>
</div>
{% endblock content %}