homepage/urls.py
from django.urls import path
from homepage.views import show_homepage, create_spot,show_spot, proxy_image, json_spots
from homepage.views import delete_spot, edit_spot, get_user_nobar_spots, create_spot_flutter
from homepage.views import delete_spot_flutter, edit_spot_flutter, json_my_spot
app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
    path('create-spot/',create_spot, name='create_spot'),
    path('spot/<str:id>/',show_spot,name='show_spot'),
    path('spot/<uuid:id>/delete', delete_spot,name='delete_spot'),
    path('json/', json_spots, name='json_spots'),
    path('json-mine/', json_my_spot, name='json_mine'),
    path('spot/<uuid:id>/edit', edit_spot, name='edit_spot'),
    path('user-spots-json/', get_user_nobar_spots, name='get_user_nobar_spots'),
    path('proxy-image/', proxy_image, name='proxy_image'),
    path('create-spot-flutter/',create_spot_flutter,name='create-spot-flutter'),
    path('delete-spot-flutter/<uuid:id>/',delete_spot_flutter,name='delete-spot-flutter'),
    path('edit-spot-flutter/<uuid:id>/', edit_spot_flutter, name='edit-spot-flutter'),
]

join/urls.py
from django.urls import path
from join.views import show_join, post_join, get_join, update_join, delete_join, create_join_flutter, update_join_flutter, delete_join_flutter

app_name = 'join'

urlpatterns = [
    path('', show_join, name='show_join'),
    path('post/<uuid:nobar_place_id>/', post_join, name='post_join'),
    path('get/', get_join, name='get_join'),
    path('update/<uuid:id>/', update_join, name='update_join'),
    path('delete/<uuid:id>/', delete_join, name='delete_join'),
    path('create-flutter/', create_join_flutter, name='create_join_flutter'),
    path('update-flutter/<uuid:id>/', update_join_flutter, name='update_join_flutter'),
    path('delete-flutter/<uuid:id>/', delete_join_flutter, name='delete_join_flutter'),
]

match/urls.py
from django.urls import path
from . import views
from .models import Competition, Match, Player
from .forms import CompetitionForm, MatchForm, PlayerForm

app_name = 'match'

urlpatterns = [
    path('api/match/get_spots/<str:match_id>/', views.get_match_spots, name="get_match_spots"),

    path('home/', views.match_main, name="match_main"),

    path('api/match/post/create_competition/', views.BasicMatchAPIView.as_view(
        model_class=Competition,
        form_class=CompetitionForm,
        opt='c'
    ), name='api_create_competition'),

    path('api/match/post/create_match/', views.BasicMatchAPIView.as_view(
        model_class=Match,
        form_class=MatchForm,
        opt='c'
    ), name='api_create_match'),

    path('api/match/post/create_player/', views.BasicMatchAPIView.as_view(
        model_class=Player,
        form_class=PlayerForm,
        opt='c'
    ), name='api_create_player'),


    path('api/match/post/update_competition/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Competition,
        form_class=CompetitionForm,
        opt='u'
    ), name='api_update_competition'),

    path('api/match/post/update_match/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Match,
        form_class=MatchForm,
        opt='u'
    ), name='api_update_match'),

    path('api/match/post/update_player/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Player,
        form_class=PlayerForm,
        opt='u'
    ), name='api_update_player'),


    path('api/match/post/delete_competition/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Competition,
        opt='d'
    ), name='api_delete_competition'),

    path('api/match/post/delete_match/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Match,
        opt='d'
    ), name='api_delete_match'),

    path('api/match/post/delete_player/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Player,
        opt='d'
    ), name='api_delete_player'),


    path('api/match/post/read_competition/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Competition,
        opt='r'
    ), name='api_read_competition'),

    path('api/match/post/read_match/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Match,
        opt='r'
    ), name='api_read_match'),

    path('api/match/post/read_player/<str:id>/', views.BasicMatchAPIView.as_view(
        model_class=Player,
        opt='r'
    ), name='api_read_player'),


    path('api/match/post/read_all_competition/', views.BasicMatchAPIView.as_view(
        model_class=Competition,
        opt='ra'
    ), name='api_read_all_competition'),

    path('api/match/post/read_all_match/', views.BasicMatchAPIView.as_view(
        model_class=Match,
        opt='ra'
    ), name='api_read_all_match'),

    path('api/match/post/read_all_player/', views.BasicMatchAPIView.as_view(
        model_class=Player,
        opt='ra'
    ), name='api_read_all_player'),


]

nobarpedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('join/', include('join.urls')),
    path('review/', include('review.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('match/', include('match.urls')),
    path('', include('homepage.urls')),
]

# Untuk serve profile picture
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.
class NobarSpot(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name=models.CharField(max_length=255)
    thumbnail = models.URLField(blank=True, null=True)
    home_team = models.CharField(max_length=50)
    away_team = models.CharField(max_length=50)
    date = models.DateField()
    time = models.TimeField()
    city = models.CharField(max_length=200)
    address = models.TextField()
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name='homepage_spots',null=True)

    def __str__(self):
        return self.name

match/models.py
from django.db import models
from homepage.models import NobarSpot
import uuid


def player_logo_image_path(instance, filename):
    return 'images/player_logos/{0}'.format(instance.id)


class Player(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    logo = models.URLField(null=True, blank=True)
    established_date = models.DateField()
    is_defunct = models.BooleanField(default=False, blank=True)


def competition_logo_image_path(instance, filename):
    return 'images/player_logos/{0}'.format(instance.id)


class Competition(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    logo = models.URLField(null=True, blank=True)
    begin_date = models.DateField()
    end_date = models.DateField()


class Match(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    competition = models.ForeignKey(to=Competition, on_delete=models.CASCADE)
    players = models.ManyToManyField(to=Player)
    shownAt = models.ManyToManyField(to=NobarSpot)
    begin_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()

homepage/forms.py
from homepage.models import NobarSpot
from django import forms
from django.utils import timezone

class NobarSpotForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        today = timezone.localdate().isoformat()
        self.fields['date'].widget.attrs['min'] = today
        
    class Meta:
        model = NobarSpot
        fields = ["name", "thumbnail","home_team","away_team","date","time","city","address"]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'w-full'}),
            'time': forms.TimeInput(attrs={'type': 'time', 'class': 'w-full'}),
            'address': forms.Textarea(attrs={'rows': 3, 'class': 'w-full'}),
        }

homepage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from homepage.forms import NobarSpotForm
from homepage.models import NobarSpot
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core import serializers
from join.models import Join_List # Import Join_List
import requests
from django.views.decorators.csrf import csrf_exempt
from django.utils.html import strip_tags
import json
from django.http import JsonResponse

# Create your views here.
def show_homepage(request):
    nobarSpot_list = NobarSpot.objects.all()
    context={
        'nobarSpot_list' : nobarSpot_list,
        'name': request.user.username,
    }
    return render(request, "homepage.html",context)

@login_required(login_url='/account/login')
def create_spot(request):
    form = NobarSpotForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        spot_entry=form.save(commit=False)
        spot_entry.host = request.user
        spot_entry.save()
        return redirect('homepage:show_homepage')
    
    context = {'form':form}
    return render(request, "create_spot.html", context)

@login_required(login_url='/account/login')
def edit_spot(request, id):
    nobarSpot = get_object_or_404(NobarSpot, pk=id)
    form = NobarSpotForm(request.POST or None, instance=nobarSpot)

    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('homepage:show_homepage')

    context = {
        'form': form
    }

    return render(request, "edit_spot.html", context)

def show_spot(request):
    nobarSpot = get_object_or_404(NobarSpot,pk=id)
    context={
        'nobarSpot' : nobarSpot
    }
    return render(request, "spot_detail.html",context)

@login_required(login_url='/account/login')
def delete_spot(request,id):
    nobarSpot = get_object_or_404(NobarSpot,pk=id)
    nobarSpot.delete()
    return HttpResponseRedirect(reverse('homepage:show_homepage'))

def json_spots(request):
    spot_list = NobarSpot.objects.all()
    data = [
        {
            'id': str(spot.id),
            'name': spot.name,
            'thumbnail': spot.thumbnail,
            'home_team':spot.home_team,
            'away_team' : spot.away_team,
            'date': spot.date,
            'time': spot.time,
            'city': spot.city,
            'address': spot.address,
            'host': spot.host.id,
            'host_username': spot.host.username,
        }
        for spot in spot_list
    ]
    return JsonResponse(data, safe=False)

def json_my_spot(request):
    spot_list = NobarSpot.objects.filter(host=request.user)
    data = [
        {
            'id': str(spot.id),
            'name': spot.name,
            'thumbnail': spot.thumbnail,
            'home_team':spot.home_team,
            'away_team' : spot.away_team,
            'date': spot.date,
            'time': spot.time,
            'city': spot.city,
            'address': spot.address,
            'host': spot.host.id,
            'host_username': spot.host.username,
        }
        for spot in spot_list
    ]
    return JsonResponse(data, safe=False)

@login_required(login_url='/account/login')
def get_user_nobar_spots(request):
    user_nobar_spots = NobarSpot.objects.filter(host=request.user)
    data = [
        {
            'id': str(spot.id),
            'name': spot.name,
            'city': spot.city,
            'time': spot.time.strftime('%H:%M') if spot.time else None,
            'host_id': str(spot.host.id),
            'host_username': spot.host.username,
            'joined_count': spot.join_list_set.count(), # Add joined count
        }
        for spot in user_nobar_spots
    ]
    return JsonResponse(data, safe=False)

def proxy_image(request):
    image_url = request.GET.get('url')
    if not image_url:
        return HttpResponse('No URL provided', status=400)
    
    try:
        # Fetch image from external source
        response = requests.get(image_url, timeout=10)
        response.raise_for_status()
        
        # Return the image with proper content type
        return HttpResponse(
            response.content,
            content_type=response.headers.get('Content-Type', 'image/jpeg')
        )
    except requests.RequestException as e:
        return HttpResponse(f'Error fetching image: {str(e)}', status=500)
    
@csrf_exempt
def create_spot_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        name = strip_tags(data.get("name", ""))  # Strip HTML tags
        thumbnail = data.get("thumbnail", "")
        home_team = strip_tags(data.get("home_team", ""))  # Strip HTML tags
        away_team = strip_tags(data.get("away_team", ""))  # Strip HTML tags
        date = data.get("date", "")
        time = data.get("time", "")
        city = strip_tags(data.get("city",""))
        address = strip_tags(data.get("address",""))
        host = request.user
        
        new_spot = NobarSpot(
            name=name, 
            thumbnail = thumbnail,
            home_team=home_team,
            away_team=away_team,
            date = date,
            time=time,
            city=city,
            address=address,
            host=host,
        )
        new_spot.save()
        
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def delete_spot_flutter(request, id):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            username = data.get("username")
            
            if not username:
                return JsonResponse({"status": "error", "message": "Username required"}, status=401)
            try:
                spot = NobarSpot.objects.get(pk=id)
            except NobarSpot.DoesNotExist:
                return JsonResponse({"status": "error", "message": "Spot not found"}, status=404)

            spot.delete()

            return JsonResponse({"status": "success", "message": "Spot deleted successfully"}, status=200)            
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=400)
    else:
        return JsonResponse({"status": "error"}, status=405)
    
@csrf_exempt
def edit_spot_flutter(request, id):
    if request.method == 'POST':
        try:
            # Cari spot berdasarkan ID
            spot = NobarSpot.objects.get(pk=id)
            
            data = json.loads(request.body)
            username = data.get('username')
            
            if spot.host.username != username:
                return JsonResponse({
                    'status': 'error',
                    'message': 'You are not authorized to edit this spot'
                }, status=403)
            
            spot.name = data.get('name', spot.name)
            spot.home_team = data.get('home_team', spot.home_team)
            spot.away_team = data.get('away_team', spot.away_team)
            spot.thumbnail = data.get('thumbnail', spot.thumbnail)
            spot.date = data.get('date', spot.date)
            spot.time = data.get('time', spot.time)
            spot.city = data.get('city', spot.city)
            spot.address = data.get('address', spot.address)
            
            spot.save()
            
            return JsonResponse({
                'status': 'success',
                'message': 'Spot updated successfully'
            }, status=200)
            
        except NobarSpot.DoesNotExist:
            return JsonResponse({
                'status': 'error',
                'message': 'Spot not found'
            }, status=404)
        except Exception as e:
            return JsonResponse({
                'status': 'error',
                'message': str(e)
            }, status=500)
    
    return JsonResponse({
        'status': 'error',
        'message': 'Invalid request method'
    }, status=405)

homepage/templates/create_modal.html
<div id="crudModal" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50">
  <div class="max-w-3xl opacity-0 mx-auto px-4 sm:px-6 lg:px-8 py-8" id="createModal">
    <div class="bg-[#333333] rounded-lg border border-gray-500 p-6 sm:p-8 form-style">
      <div class="mb-8">
        <h1 class="text-2xl tracking-wide text-white mb-2 text-center">Add New Match</h1>
      </div>
      <form id="comp_form" class="space-y-6">
        <input type="hidden" name="csrfmiddlewaretoken" value="FyemG3RJW5kS3zlz8vsbqwgafUQYdr5KOYIjmkpXG6kTvQwQIGoSWAKHwoFOTeY1">
        <div>
          <label for="id_competition" class="block text-sm font-medium text-white mb-2">
            Competition
          </label>
          <div class="w-full">
            <select name="competition" required id="id_competition" onchange="getPlayersForCompetition()" 
                    class="w-full bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block p-2.5 placeholder-gray-400">
               <option value="" selected>Select a competition...</option>
               </select>
          </div>
        </div>
        <div>
          <label for="id_players" class="block text-sm font-medium text-white mb-2">
            Players
          </label>
          <div class="w-full">
            <select name="players" required id="id_players" multiple 
                    class="w-full bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block p-2.5 placeholder-gray-400 h-32">
              </select>
          </div>
        </div>
        <div>
          <label for="id_begin_datetime" class="block text-sm font-medium text-white mb-2">
            Begin datetime
          </label>
          <div class="w-full">
            <input type="date" name="begin_datetime" id="id_begin_datetime" 
                   class="w-full bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block p-2.5 placeholder-gray-400">
          </div>
        </div>
        <div>
          <label for="id_end_datetime" class="block text-sm font-medium text-white mb-2">
            End datetime
          </label>
          <div class="w-full">
            <input type="date" name="end_datetime" id="id_end_datetime" 
                   class="w-full bg-gray-700 border border-gray-600 text-white text-sm rounded-lg focus:ring-green-500 focus:border-green-500 block p-2.5 placeholder-gray-400">
          </div>
        </div>
        <div class="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-500">
          <button onclick="hideCreateModal()" class="order-2 sm:order-1 px-6 py-3 border border-gray-500 text-gray-300 rounded-md font-medium hover:bg-gray-700 hover:text-white transition-colors text-center">
            Cancel
          </button>
          <button type="button" onclick="addMatchEntry()" class="order-1 sm:order-2 flex-1 bg-green-600 text-white px-6 py-3 rounded-md font-medium hover:bg-green-700 transition-colors shadow-lg shadow-green-900/50">
            Create Match
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
const competition_options = document.querySelector('#id_competition');
const player_options = document.querySelector('#id_players');
const modalParent = document.getElementById("crudModal");
const createModal = document.getElementById("createModal");

function showCreateModal() {
  modalParent.classList.remove("hidden");
  setTimeout(() => {
    createModal.classList.remove('opacity-0', 'scale-95');
    createModal.classList.add('opacity-100', 'scale-100');
  }, 50); 
}

function hideCreateModal() {
  modalParent.classList.add("hidden");
  createModal.classList.remove('opacity-100', 'scale-100');
  createModal.classList.add('opacity-0', 'scale-95');
}


function setCompetitionSelections(data) {
    competition_options.innerHTML = "";
    for (const item of data) {
        const id = item.pk;
        const name = DOMPurify.sanitize(item.fields.name);
        const option = document.createElement('option');
        option.setAttribute("value", id);
        option.innerHTML = name;
        competition_options.appendChild(option);
    }
}

function setPlayerSelections(data) {
    const currentSelection = Array.from(player_options.selectedOptions).map(option => option.value);
    player_options.innerHTML = "";
    for (const item of data) {
        const id = item.pk;
        const name = DOMPurify.sanitize(item.fields.name);
        const option = document.createElement('option');
        option.setAttribute("value", id);
        option.innerHTML = name;
        if (currentSelection.includes(option.value)) {
            option.selected = true;
        }
        player_options.appendChild(option);
    }
}

async function getCompetitionOptions() {
    try {
        const response = await fetch("{% url 'match:api_read_all_competition' %}", {
            headers: { 'Accept': 'application/json' },
        });

        if (!response.ok) {
            throw new Error('Failed to fetch data from server');
        }
        const matchData = await response.json();
        setCompetitionSelections(JSON.parse(matchData || []));
    } catch (error) {
        console.error('Error loading', error);
    }
}

async function getPlayerOptions() {
    try {
        const response = await fetch("{% url 'match:api_read_all_player' %}", {
            headers: { 'Accept': 'application/json' },
        });

        if (!response.ok) {
            throw new Error('Failed to fetch data from server');
        }
        const matchData = await response.json();
        setPlayerSelections(JSON.parse(matchData || []));
    } catch (error) {
        console.error('Error loading', error);
    }
}

async function addMatchEntry() {
    await fetch("{% url 'match:api_create_match' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#comp_form')),
    })
    document.getElementById("comp_form").reset();
    hideCreateModal();
}

document.addEventListener('DOMContentLoaded', getPlayerOptions)
document.addEventListener('DOMContentLoaded', getCompetitionOptions)
</script>

homepage/templates/create_spot.html
{% extends 'base.html' %}
{% block meta %}
<title>Add Product - Flex Kick</title>
{% endblock meta %}

{% block content %}
<div class="bg-[#1E1E1E] w-full min-h-screen">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    
    <!-- Back Navigation -->
    <div class="mb-6">
      <a href="{% url 'homepage:show_homepage' %}" class="text-gray-300 hover:text-white font-medium transition-colors">
        ← Back to Product
      </a>
    </div>
    
    <!-- Form -->
    <div class="bg-[#333333] rounded-lg border border-gray-500 p-6 sm:p-8 form-style">
      <div class="mb-8">
        <h1 class="text-2xl tracking-wide text-white mb-2 text-center">Add New Spot</h1>
      </div>
      
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div>
            <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-white mb-2">
              {{ field.label }}
            </label>
            <div class="w-full text-black">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        
        <div class="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-200">
          <a href="{% url 'homepage:show_homepage' %}" class="order-2 sm:order-1 px-6 py-3 border border-gray-300 text-white rounded-md font-medium hover:bg-gray-50 hover:text-gray-800 transition-colors text-center">
            Cancel
          </a>
          <button type="submit" class="order-1 sm:order-2 flex-1 bg-green-600 text-white px-6 py-3 rounded-md font-medium hover:bg-green-800 transition-colors">
            Publish Spot
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

homepage/templates/edit_spot.html
{% extends 'base.html' %}
{% block meta %}
<title>Add Product - Flex Kick</title>
{% endblock meta %}

{% block content %}
<div class="bg-[#1E1E1E] w-full min-h-screen">
  <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    
    <!-- Back Navigation -->
    <div class="mb-6">
      <a href="{% url 'homepage:show_homepage' %}" class="text-gray-300 hover:text-white font-medium transition-colors">
        ← Back
      </a>
    </div>
    
    <!-- Form -->
    <div class="bg-[#333333] rounded-lg border border-gray-500 p-6 sm:p-8 form-style">
      <div class="mb-8">
        <h1 class="text-2xl tracking-wide text-white mb-2 text-center">Add New Spot</h1>
      </div>
      
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div>
            <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-white mb-2">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        
        <div class="flex flex-col sm:flex-row gap-4 pt-6 border-t border-gray-200">
          <a href="{% url 'homepage:show_homepage' %}" class="order-2 sm:order-1 px-6 py-3 border border-gray-300 text-white rounded-md font-medium hover:bg-gray-50 hover:text-gray-800 transition-colors text-center">
            Cancel
          </a>
          <button type="submit" class="order-1 sm:order-2 flex-1 bg-green-600 text-white px-6 py-3 rounded-md font-medium hover:bg-green-800 transition-colors">
            Publish Spot
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}